### ISSUE TITLE
Can't build with WSL

### ISSUE THREAD

**Issue by mimikun** [triyanox/lla#47]
I was able to build it this A.M 11, but now I can't.

### env
Ubuntu 22.04(WSL2)
Windows11 24H2
rustc 1.85.0-nightly (33c245b9e 2024-12-10)

### Log

```txt
❯ cargo install lla

    Updating crates.io index
  Installing lla v0.3.0
    Updating crates.io index
     Locking 145 packages to latest compatible versions
      Adding clap v3.2.25 (available: v4.5.23)
      Adding dashmap v5.5.3 (available: v6.1.0)
      Adding prost v0.12.6 (available: v0.13.4)
      Adding strip-ansi-escapes v0.1.1 (available: v0.2.0)
      Adding terminal_size v0.3.0 (available: v0.4.1)
      Adding unicode-width v0.1.14 (available: v0.2.0)
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling autocfg v1.4.0
   Compiling libc v0.2.168
   Compiling rustix v0.38.42
   Compiling anyhow v1.0.94
   Compiling either v1.13.0
   Compiling serde v1.0.216
   Compiling memchr v2.7.4
   Compiling prettyplease v0.2.25
   Compiling crossbeam-utils v0.8.20
   Compiling hashbrown v0.15.2
   Compiling cfg-if v1.0.0
   Compiling itertools v0.12.1
   Compiling bitflags v2.6.0
   Compiling bytes v1.9.0
   Compiling regex-syntax v0.8.5
   Compiling equivalent v1.0.1
   Compiling linux-raw-sys v0.4.14
   Compiling fastrand v2.3.0
   Compiling fixedbitset v0.4.2
   Compiling aho-corasick v1.1.3
   Compiling indexmap v2.7.0
   Compiling once_cell v1.20.2
   Compiling lock_api v0.4.12
   Compiling quote v1.0.37
   Compiling lazy_static v1.5.0
   Compiling heck v0.5.0
   Compiling multimap v0.10.0
   Compiling syn v2.0.90
   Compiling log v0.4.22
   Compiling parking_lot_core v0.9.10
   Compiling crossbeam-epoch v0.9.18
   Compiling petgraph v0.6.5
   Compiling indexmap v1.9.3
   Compiling num-traits v0.2.19
   Compiling scopeguard v1.2.0
   Compiling smallvec v1.13.2
   Compiling rayon-core v1.12.1
   Compiling unicode-width v0.1.14
   Compiling thiserror v1.0.69
   Compiling portable-atomic v1.10.0
   Compiling serde_json v1.0.133
   Compiling console v0.15.8
   Compiling crossbeam-deque v0.8.5
   Compiling regex-automata v0.4.9
   Compiling vte_generate_state_changes v0.1.2
   Compiling ryu v1.0.18
   Compiling itoa v1.0.14
   Compiling os_str_bytes v6.6.1
   Compiling tempfile v3.14.0
   Compiling arrayvec v0.5.2
   Compiling option-ext v0.2.0
   Compiling winnow v0.6.20
   Compiling hashbrown v0.12.3
   Compiling utf8parse v0.2.2
   Compiling dirs-sys v0.4.1
   Compiling vte v0.10.1
   Compiling clap_lex v0.2.4
   Compiling atty v0.2.14
   Compiling hashbrown v0.14.5
   Compiling shell-words v1.1.0
   Compiling bitflags v1.3.2
   Compiling regex v1.11.1
   Compiling iana-time-zone v0.1.61
   Compiling zeroize v1.8.1
   Compiling unicode-width v0.2.0
   Compiling number_prefix v0.4.0
   Compiling termcolor v1.4.1
   Compiling same-file v1.0.6
   Compiling textwrap v0.16.1
   Compiling strsim v0.10.0
   Compiling rayon v1.10.0
   Compiling walkdir v2.5.0
   Compiling indicatif v0.17.9
   Compiling clap v3.2.25
   Compiling dashmap v5.5.3
   Compiling chrono v0.4.39
   Compiling users v0.11.0
   Compiling strip-ansi-escapes v0.1.1
   Compiling terminal_size v0.3.0
   Compiling dirs v5.0.1
   Compiling parking_lot v0.12.3
   Compiling colored v2.1.0
   Compiling prost-derive v0.12.6
   Compiling serde_derive v1.0.216
   Compiling thiserror-impl v1.0.69
   Compiling libloading v0.8.6
   Compiling glob v0.3.1
   Compiling prost v0.12.6
   Compiling dialoguer v0.11.0
   Compiling prost-types v0.12.6
   Compiling prost-build v0.12.6
   Compiling lla_plugin_interface v0.3.0
error: failed to run custom build command for `lla_plugin_interface v0.3.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installoGRuib/release/build/lla_plugin_interface-6f63bfa8a913375d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/mimikun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lla_plugin_interface-0.3.0/build.rs:2:67:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: plugin.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lla v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installoGRuib`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by triyanox** [comment]
Hey there @zachvalenta @mimikun in the latest release `lla` uses `protobuf` serialization for communication between host and plugins, here's a quick fix for both platforms while I'm preparing documentation and a permanant fix that doesn't require any input on build

## macOS
```bash
# Install protobuf
brew install protobuf
```

## Linux
```bash
# Debian/Ubuntu
sudo apt update && sudo apt install -y protobuf-compiler

# If you get proto3 optional fields error:
export PROTOC_OPTS="--experimental_allow_proto3_optional"
```

Let me know if the fix worked for you

**Comment by zachvalenta** [comment]
Is [this](https://github.com/users/triyanox/projects/2/views/3?pane=issue&itemId=90538517) the project ticket we should track for that fix?

**Comment by zachvalenta** [comment]
Also, despite the current protobuf thing, great project. The flags:

* size map `-S`
* timeline `--timeline`
* git commit `-G`

are ones I don't think I've seen in any of the competitors ([eza](https://github.com/eza-community/eza), [lsd](https://github.com/lsd-rs/lsd), [pls](https://pls.cli.rs/)). Very cool stuff.

**Comment by triyanox** [comment]
I created ticket for it [here](https://github.com/users/triyanox/projects/2/views/3?pane=issue&itemId=90595966) I'm already working on it.

And thank you @zachvalenta glad you found it useful there is more to come for the upcoming releases for sure!

**Comment by triyanox** [comment]
I have merged the pull request that fixes this problem #49 you can just give it try and it will work without any issues, if you need further assistant let me know!

**Comment by zachvalenta** [comment]
I'm still getting the same error. For a bit of context, earlier in the day I ran `rustup update` in an attempt to debug:

```sh
$ rustup update
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-11-28, rust version 1.83.0 (90b35a623 2024-11-26)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
 25.7 MiB /  25.7 MiB (100 %)  16.0 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 53.1 MiB /  53.1 MiB (100 %)   9.8 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 16.5 MiB /  16.5 MiB (100 %)   7.3 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 25.7 MiB /  25.7 MiB (100 %)  20.5 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 53.1 MiB /  53.1 MiB (100 %)  22.3 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'
info: checking for self-update
stable-aarch64-apple-darwin updated - rustc 1.83.0 (90b35a623 2024-11-26) (from rustc 1.82.0 (f6e511eec 2024-10-15))
info: cleaning up downloads & tmp directories
```

Ran it again just now, much more limited output:

```sh
$ rustup update

info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: checking for self-update
stable-aarch64-apple-darwin unchanged - rustc 1.83.0 (90b35a623 2024-11-26)
info: cleaning up downloads & tmp directories
```

But in both cases didn't prove to prevent/solve the error.

**Comment by zachvalenta** [comment]
Also, bit more context: I came across `lla` on [Terminal Trove](https://terminaltrove.com/lla/) (they do a [weekly newsletter](https://terminaltrove.com/new/) and you were in it) yesterday at work and downloaded onto that machine no problem, so maybe a commit in the past 24-ish hours? [This one](https://github.com/triyanox/lla/commit/3764370b9df01fbe86f2a51df61953586b690ea9) looks like a potential culprit.

**Comment by triyanox** [comment]
Quite a few tools in my setup I discovered on [Terminal Trove](https://terminaltrove.com/lla/), Terminal Trove and The Console are great newsletters

@zachvalenta did you pull the latest changes?

**Comment by triyanox** [comment]
Hey there @zachvalenta @mimikun this issue is already fixed you can check https://github.com/triyanox/lla/issues/36, also no need for protoc or protobuf-compiler the bindings are already generated in #51 , thank you for taking the time to open this issue.

**Comment by zachvalenta** [comment]
great to hear!
